### ISSUE TITLE
Making our images publicly-available

### ISSUE THREAD

**Issue by gwaybio** [broadinstitute/profiling-resistance-mechanisms#122]
As we work towards publication, we also need to work towards making our data publicly available. The bulk profiles are [already available](https://github.com/broadinstitute/profiling-resistance-mechanisms/tree/master/0.generate-profiles/profiles), but it is a larger push to make our images public.

The group discussed this process today, and @shntnu recommended CellPainting gallery.

In this issue, we can discuss:

1. Selecting batches to upload (which do we include in the manuscript, some were pilot batches),
2. Thawing data
3. Moving to the gallery
4. Adding fluorescence and brightfield images

**Comment by mekelley** [comment]
I have a spreadsheet correlating batches with plate number and experimental conditions going back to batch 8. I can keep adding plates from batches 7 and earlier if they're included in the final dataset. Let me know:

https://docs.google.com/spreadsheets/d/1kCvDYi8K4CKlLRnD9nVITuAUR-gGn_tnjmC9pMTD-Dk/edit?usp=sharing

Not included in the spreadsheet are the brightfield plate numbers since we didn't end up using them but I can dig those numbers up if necessary

**Comment by gwaybio** [comment]
Nice! @mekelley - this seems very relevant to point 1: Selecting batches to upload. 

> I can keep adding plates from batches 7 and earlier if they're included in the final dataset. Let me know:

Are we going to include data from batch 7 and earlier? I suppose when I track back through some of the analyses you point me towards, we'll know for sure.

**Comment by gwaybio** [comment]
@shntnu - pinging to make sure this is on your radar. It would be great to add this to RODA! Do you think that would be possible?

**Comment by shntnu** [comment]
@gwaybio This was, but buried :)

I've kicked things off in https://github.com/broadinstitute/cellpainting-gallery/issues/49#issuecomment-1611529374
