### ISSUE TITLE
What is the best way to select Profiling Variables?

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/profiling-resistance-mechanisms#9]
In working through #1 and #8 I thought about how I would combine data from batches together. My two options seemed to be:

1. Take feature union
2. Take feature intersection

The problem with taking the feature intersection is that fewer features are selected. The problem with taking feature union is that some variables may not be "good" features.

What is the method for cell painting variable selection? If the features are removed b/c of lack of consistency across replicates, then they should not be included in the feature union. However, if the features are removed because they are deemed redundant, then they _should_ be included in the feature union.

@shntnu is there any way to track the decisions for feature selection?

**Comment by gwaygenomics** [comment]
I have realized that a lot of the information can be found in [the profiling handbook](https://cytomining.github.io/profiling-handbook/create-profiles.html#select-variables)

**Comment by shntnu** [comment]
Ine

> I have realized that a lot of this information can be found in [the profiling handbook](https://cytomining.github.io/profiling-handbook/create-profiles.html#select-variables).

Yep, albeit terse :) 
> To actually apply variable selection, we compute the intersection of all these variable lists

**Comment by shntnu** [comment]
> The problem with taking the feature intersection is that fewer features are selected. The problem with taking feature union is that some variables may not be "good" features.

Our current practice is to do one of these, both have problems:
(1) Use a "standard" variable list that was generated on a much larger dataset, e.g. the drug repurposing set (unpublished), or the [CDRP](https://academic.oup.com/gigascience/article/6/12/giw014/2865213) dataset (selected features are not publicly available, but can easily do so)

(2) Redo variable selection when combining batches

For now, I would recommend doing (2) until we figure out a better way to do this. I would not recommend union or intersection because it is probably worse that doing (2).

**Comment by gwaygenomics** [comment]
> (2) Redo variable selection when combining batches

For now, I would recommend doing (2) until we figure out a better way to do this. I would not recommend union or intersection because it is probably worse that doing (2).

Gotcha! So this step will be run when each batch of new data comes in?

**Comment by shntnu** [comment]
> Gotcha! So this step will be run when each batch of new data comes in?

Yep
